-/*-------------------------------88888888888888888888----*/
-window.setInterval(function(){
-
-var today = new Date();
- var h = today.getHours();
- var m = today.getMinutes();
- var s = today.getSeconds();
-console.log(h+":"+m+":"+s);
- }, 1000);
